Nulmeeting - Levarne - Thijs
LeVarneBV/Nulmeting-Frontend-2023 pull request #3
Opened 2023-09-06 15:01 UTC by Thidges

De minimum requirements is me allemaal gelukt.
Ik was bezig met het proberen om op verschillende manieren te kunnen sorteren. Dat is me alleen helaas niet gelukt. Het is gebleven bij sorteren op datum. Als je ziet wat er fout ging dan hoor ik dat graag.

(P.s. Ik snap dat deze PR niet met de base repository gemerged moet worden, maar op mijn eigen repo was ik alleen bezig op de master branch.)

2023-09-11 11:41 UTC, YYvdLaak requested changes
Nice! Paar kleine puntjes nog 🔍

2023-09-11 11:41 UTC, YYvdLaak commented on stores/todo.ts
> +    'x-api-key': '6AgP2Gr7j3QvJHIr7xOq4OlY5McyScy3kqQL5Mr7'
whoops 🙈

2023-09-11 11:41 UTC, YYvdLaak commented on stores/todo.ts
> +      const promiseTodoItem: Promise<TodoItem> = axios.request(config)
Voor het ophalen van data van een server kun je `useFetch` gebruiken, een composable die standaard met Vue meegeleverd wordt: https://nuxt.com/docs/api/composables/use-fetch

2023-09-11 11:41 UTC, YYvdLaak commented on pages/index.vue
> +<script lang="ts">
In principe hoeven we geen losse <script setup lang="ts"> en <script lang="ts"> tags te hebben. Je kan alles gewoon onder <script setup> zetten.

2023-09-11 11:41 UTC, YYvdLaak commented on pages/index.vue
> +        </select>
Deze kan je dmv v-model koppelen aan een variabele die in je <script setup> deel staat, en dan obv daarvan de todos computed property berekenen. Dan zul je zien dat als je een sorteer optie selecteerd, die computed property automatisch update 👀 

https://vuejs.org/guide/essentials/forms.html#text

2023-09-12 06:30 UTC, Thidges commented on stores/todo.ts
> +    'x-api-key': '6AgP2Gr7j3QvJHIr7xOq4OlY5McyScy3kqQL5Mr7'
Dit hoorde ik te weten, heb ik gelezen. Slordig puntje van mij

2023-10-20 13:46 UTC, closed without merging